apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GeoNorgeAPI
  tags:
    - public
spec:
  type: library
  lifecycle: production
  owner: group:default/geonorge
  system: system:default/geonorge
