# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "GeoNorgeAPI"
  tags:
  - "public"
spec:
  type: "library"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
